-- =========================================
-- Definição das funções do banco de dados
-- =========================================

CREATE OR REPLACE FUNCTION VALIDAR_PECA()
RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.VALOR_UNITARIO <= 0) THEN
        RAISE EXCEPTION 'O VALOR UNITÁRIO DA PEÇA DEVE SER MAIOR QUE ZERO.';
    ELSIF (NEW.ESTOQUE <= 0) THEN
        RAISE EXCEPTION 'A QUANTIDADE EM ESTOQUE DEVE SER MAIOR QUE ZERO.';
    ELSIF NOT EXISTS (SELECT 1 FROM FABRICANTE_PECA WHERE ID_FABRICANTE = NEW.ID_FABRICANTE) THEN
        RAISE EXCEPTION 'FABRICANTE INFORMADO NÃO ENCONTRADO NO CADASTRO.';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_PECA(
    P_ID_PECA INT, P_ID_FABRICANTE INT, P_NOME VARCHAR, P_VALOR_UNITARIO FLOAT, P_ESTOQUE INT
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO PECA (ID_PECA, ID_FABRICANTE, NOME, VALOR_UNITARIO, ESTOQUE) 
    VALUES (P_ID_PECA, P_ID_FABRICANTE, P_NOME, P_VALOR_UNITARIO, P_ESTOQUE);
    
    RAISE NOTICE 'SUCESSO: PEÇA "%" CADASTRADA COM % UNIDADE(S) A R$ % CADA.', 
                 P_NOME, P_ESTOQUE, P_VALOR_UNITARIO;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION REPOR_ESTOQUE(
	P_ID_PECA INT,
 	P_QUANTIDADE INT
)
RETURNS VOID AS $$
DECLARE
	V_NOME_PECA VARCHAR;
	V_ESTOQUE_ANT INT;
	V_ESTOQUE_NOV INT;
BEGIN

	IF (P_QUANTIDADE <= 0) THEN
		RAISE EXCEPTION 'A QUANTIDADE A REPOR DEVE SER MAIOR QUE ZERO.';
	END IF;


	IF NOT EXISTS (SELECT 1 FROM PECA WHERE ID_PECA = P_ID_PECA) THEN
		RAISE EXCEPTION 'PEÇA COM ID % NÃO ENCONTRADA.', P_ID_PECA;
	END IF;
	
	SELECT NOME, ESTOQUE INTO V_NOME_PECA, V_ESTOQUE_ANT FROM PECA WHERE ID_PECA = P_ID_PECA;

	UPDATE PECA
	SET ESTOQUE = ESTOQUE + P_QUANTIDADE
	WHERE ID_PECA = P_ID_PECA
	RETURNING ESTOQUE INTO V_ESTOQUE_NOV;

	RAISE NOTICE 'SUCESSO: "%" | ESTOQUE ANTERIOR: % -> NOVO ESTOQUE: % (+% UNIDADE(S)).',
		V_NOME_PECA, V_ESTOQUE_ANT, V_ESTOQUE_NOV, P_QUANTIDADE;

END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CALCULAR_COMISSAO(ID_FUNC INT, ANO INT, MES INT)
RETURNS TABLE (
valor_comissao FLOAT
)
AS $$
DECLARE
	O_ANO INT;
	O_MES INT;
BEGIN	
	SELECT EXTRACT (YEAR FROM DT_FECHA_OS) INTO O_ANO
	FROM OS WHERE DT_FECHA_OS IS NOT NULL AND 
	EXTRACT(YEAR FROM DT_FECHA_OS) = ANO;
	
	SELECT EXTRACT (MONTH FROM DT_FECHA_OS) INTO O_MES
	FROM OS WHERE DT_FECHA_OS IS NOT NULL AND 
	EXTRACT(MONTH FROM DT_FECHA_OS) = MES;

	RETURN QUERY
	SELECT (SUM(S.VALOR) * COMISSAO) VALOR_COMISSAO
	FROM OS O JOIN SERVICO S ON O.ID_SERVICO = S.ID_SERVICO
	JOIN FUNCIONARIO F ON S.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN CARGO C ON F.ID_CARGO = C.ID_CARGO
	WHERE DT_FECHA_OS IS NOT NULL AND F.ID_FUNCIONARIO = ID_FUNC AND
	EXTRACT(YEAR FROM DT_FECHA_OS) = O_ANO AND EXTRACT(MONTH FROM DT_FECHA_OS) = O_MES
	GROUP BY F.ID_FUNCIONARIO,F.NOME,COMISSAO
	ORDER BY VALOR_COMISSAO DESC;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION VALIDAR_FUNCIONARIO()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_FUNCIONARIO IS NULL) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NULO';
ELSIF (NEW.ID_FUNCIONARIO < 0) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE ID_FUNCIONARIO = NEW.ID_FUNCIONARIO) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER DUPLICADO';
ELSIF (NEW.ID_CARGO IS NULL) THEN
RAISE EXCEPTION 'ID DO CARGO NÃO PODE SER NULO';
ELSIF (NEW.ID_CARGO < 0) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NEGATIVO';
ELSIF NOT EXISTS (SELECT ID_CARGO FROM CARGO WHERE ID_CARGO = NEW.ID_CARGO) THEN
RAISE EXCEPTION 'ID DO CARGO PRECISA ESTAR CADASTRADO';
ELSIF (NEW.CPF IS NULL) THEN
RAISE EXCEPTION 'O CPF INFORMADO NÃO DEVE SER NULO';
ELSIF (LENGTH(NEW.CPF) <> 11) THEN 
RAISE EXCEPTION 'O CPF CADASTRADO DEVE TER 11 DIGITOS';
ELSIF EXISTS(SELECT CPF FROM FUNCIONARIO WHERE CPF = NEW.CPF) THEN
RAISE EXCEPTION 'O CPF CADASTRADO NÃO PODE SER DUPLICADO';
ELSIF (NEW.NOME IS NULL) THEN
RAISE EXCEPTION 'O NOME DO FUNCIONARIO NÃO PODE SER NULO';
ELSIF (NEW.SALARIO IS NULL) THEN
RAISE EXCEPTION 'O SALARIO DO FUNCIONÁRIO NÃO PODE SER NULO';
ELSIF (NEW.SALARIO < 1621.00) THEN
RAISE EXCEPTION 'O FUNCIONÁRIO TEM DIREITO A PELO MENOS UM SALÁRIO MINIMO';
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_VEICULO(ID_CLI INT,ID_VEI INT,ID_MOD INT,PLACA VARCHAR, ANO INT, COR VARCHAR)
RETURNS VOID AS $$
DECLARE
	M_POSSE INT;
BEGIN
SELECT MAX(ID_POSSE) INTO M_POSSE FROM POSSE; 
IF NOT EXISTS(SELECT ID_CLIENTE FROM CLIENTE WHERE ID_CLIENTE = ID_CLI) THEN
RAISE EXCEPTION 'RELACIONE UM CLIENTE EXISTENTE PARA A POSSE DO VEICULO';
ELSIF EXISTS (SELECT ID_VEICULO,ID_CLIENTE FROM POSSE WHERE ID_VEICULO =
ID_VEI AND ID_CLIENTE = ID_CLI) THEN
RAISE EXCEPTION 'ESSE RELAÇÃO DE POSSE JÁ ESTÁ CADASTRADA';
ELSE
INSERT INTO VEICULO VALUES
(ID_VEI,ID_MOD,PLACA,ANO,COR);
INSERT INTO POSSE VALUES
(M_POSSE + 1,ID_VEI,ID_CLI);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO'
END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION VALIDAR_VEICULO()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_VEICULO IS NULL) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER NULO';
ELSIF (NEW.ID_VEICULO < 0) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_VEICULO FROM VEICULO WHERE ID_VEICULO = NEW.ID_VEICULO) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER DUPLICADO';
ELSIF (NEW.ID_MODELO IS NULL) THEN
RAISE EXCEPTION 'O ID DE MODELO NÃO PODE SER NULO';
ELSIF (NEW.ID_MODELO < 0) THEN
RAISE EXCEPTION 'O ID DE MODELO NÃO PODE SER NEGATIVO';
ELSIF NOT EXISTS (SELECT ID_MODELO FROM MODELO WHERE ID_MODELO = NEW.ID_MODELO) THEN
RAISE EXCEPTION 'O ID DE MODELO PRECISA ESTAR CADASTRADO NO SISTEMA';
ELSIF (NEW.PLACA IS NULL) THEN
RAISE EXCEPTION 'A PLACA INFORMADA NÃO PODE SER NULA';
ELSIF (LENGTH(NEW.PLACA) <> 7) THEN
RAISE EXCEPTION 'A PLACA INFORMADA DEVE TER 7 DIGITOS';
ELSIF (NEW.ANO IS NULL) THEN
RAISE EXCEPTION  'O ANO INFORMADO NÃO PODE SER NULL';
ELSIF (NEW.ANO < 1886 OR NEW.ANO > EXTRACT(YEAR FROM CURRENT_DATE)) THEN
RAISE EXCEPTION 'INSIRA UM ANO DENTRO DE UM LIMITE VALIDO (ENTRE 1886 E O ANO ATUAL)';
ELSIF (NEW.COR IS NULL) THEN
RAISE EXCEPTION 'A COR INFORMADA NÃO PODE SER NULA';
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION CADASTRAR_CLIENTE(ID_CLI INT, CPF VARCHAR, NOME VARCHAR, TELEFONE VARCHAR, EMAIL VARCHAR)
RETURNS VOID AS $$
BEGIN
INSERT INTO CLIENTE VALUES
(ID_CLI,CPF,NOME,TELEFONE,EMAIL);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_FUNCIONARIO(ID_FUNC INT,ID_CAR INT,CPF VARCHAR, NOME VARCHAR, SALARIO FLOAT)
RETURNS VOID AS $$
BEGIN
INSERT INTO FUNCIONARIO VALUES
(ID_FUNC,ID_CAR,CPF,NOME,SALARIO);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO';
END;
$$ LANGUAGE plpgsql;

-- FUNCTIONS E TRIGGERS DE VALIDAÇÃO
CREATE OR REPLACE FUNCTION VALIDAR_CLIENTE()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_CLIENTE IS NULL) THEN
RAISE EXCEPTION 'O ID DE CLIENTE NÃO PODE SER NULO';
ELSIF (NEW.ID_CLIENTE < 0) THEN
RAISE EXCEPTION 'O ID DE CLIENTE NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_CLIENTE FROM CLIENTE WHERE ID_CLIENTE = NEW.ID_CLIENTE) THEN
RAISE EXCEPTION 'NÃO SÃO PERMITIDOS IDS DUPLICADOS';
ELSIF (NEW.CPF IS NULL) THEN
RAISE EXCEPTION 'O CPF DE CLIENTE NÃO PODE SER NULO';
ELSIF (LENGTH(NEW.CPF) <> 11) THEN
RAISE EXCEPTION 'O CPF INFORMADO DEVE TER 11 DIGITOS';
ELSIF EXISTS(SELECT CPF FROM CLIENTE WHERE CPF = NEW.CPF) THEN
RAISE EXCEPTION 'NÃO SÃO PERMITIDOS CPFS DUPLICADOS';
ELSIF (NEW.NOME IS NULL) THEN
RAISE EXCEPTION 'O NOME INFORMADO NÃO PODE SER NULO';
ELSIF (NEW.TELEFONE IS NULL) THEN
RAISE EXCEPTION 'O TELEFONE INFORMADO NÃO PODE SER NULO';
ELSIF (LENGTH(NEW.TELEFONE) <> 13) THEN
RAISE EXCEPTION 'O TELEFONE DEVE TER 13 DIGITOS';
ELSIF (NEW.EMAIL IS NULL) THEN
RAISE EXCEPTION 'O EMAIL INFORMADO NÃO PODE SER NULO';
ELSIF (NEW.EMAIL NOT ILIKE '%@email.com') THEN
RAISE EXCEPTION 'O EMAIL INFORMADO PRECISA ESTAR NO FORMATO CORRETO';

END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DISPARAR_ALERTA_ESTOQUE()
RETURNS TRIGGER AS $$
DECLARE
    V_LIMITE_PADRAO INT := 25; 
BEGIN

    IF (NEW.ESTOQUE <= V_LIMITE_PADRAO AND NEW.ESTOQUE < OLD.ESTOQUE) THEN
        
        RAISE WARNING 'ALERTA DE ESTOQUE!!!!: A peça "%" (ID: %) caiu para % unidades!', 
			NEW.NOME, NEW.ID_PECA, NEW.ESTOQUE;
                      
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CALCULAR_COMISSAO_FUNCIONARIO(P_ID_FUNCIONARIO INT)
RETURNS FLOAT AS $$
DECLARE
    V_NOME_FUNC  VARCHAR;
    V_NOME_CARGO VARCHAR;
    V_SALARIO    FLOAT;
    V_COMISSAO   FLOAT;
    V_RESULTADO  FLOAT;
BEGIN


    IF NOT EXISTS (SELECT 1 FROM FUNCIONARIO WHERE ID_FUNCIONARIO = P_ID_FUNCIONARIO) THEN
        RAISE EXCEPTION 'FUNCIONÁRIO COM ID % NÃO ENCONTRADO.', P_ID_FUNCIONARIO;
    END IF;

    SELECT F.NOME, C.NOME, F.SALARIO, C.COMISSAO
    INTO V_NOME_FUNC, V_NOME_CARGO, V_SALARIO, V_COMISSAO
    FROM FUNCIONARIO F
    JOIN CARGO C ON C.ID_CARGO = F.ID_CARGO
    WHERE F.ID_FUNCIONARIO = P_ID_FUNCIONARIO;

    V_RESULTADO := V_SALARIO * V_COMISSAO;

    RAISE NOTICE 'FUNCIONÁRIO: % | CARGO: % | SALÁRIO: R$% | COMISSÃO (% %%): R$%',
        V_NOME_FUNC, V_NOME_CARGO, V_SALARIO,(V_COMISSAO * 100), V_RESULTADO;

    RETURN V_RESULTADO;
END;
$$ LANGUAGE PLPGSQL;

