-- =========================================
-- Definição das triggers do banco de dados
-- =========================================

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_PECA
BEFORE INSERT OR UPDATE ON PECA 
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_PECA();

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_FUNCIONARIO
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_FUNCIONARIO();


CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_VEICULO
BEFORE INSERT ON VEICULO
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_VEICULO();

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_CLIENTE();
SELECT * FROM CLIENTE;

CREATE OR REPLACE TRIGGER TRIGGER_ALERTA_ESTOQUE
AFTER UPDATE ON PECA
FOR EACH ROW
EXECUTE PROCEDURE DISPARAR_ALERTA_ESTOQUE();