-- =========================================
-- Projeto final completo do banco de dados
-- =========================================

-- CRIAÇÃO DAS TABELAS
CREATE TABLE FABRICANTE_MARCA(
ID_FABRICANTE INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL);

CREATE TABLE MARCA(
ID_MARCA INT NOT NULL PRIMARY KEY,
ID_FABRICANTE INT NOT NULL REFERENCES FABRICANTE_MARCA(ID_FABRICANTE),
NOME VARCHAR(50) NOT NULL);

CREATE TABLE MODELO(
ID_MODELO INT NOT NULL PRIMARY KEY,
ID_MARCA INT NOT NULL REFERENCES MARCA(ID_MARCA),
NOME VARCHAR(50) NOT NULL);

CREATE TABLE VEICULO(
ID_VEICULO INT NOT NULL PRIMARY KEY,
ID_MODELO INT NOT NULL REFERENCES MODELO(ID_MODELO),
PLACA VARCHAR(7) NOT NULL, 
ANO INT NOT NULL,
COR VARCHAR(50) NOT NULL);

CREATE TABLE CARGO(
ID_CARGO INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
COMISSAO FLOAT NOT NULL);

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT NOT NULL PRIMARY KEY,
ID_CARGO INT NOT NULL REFERENCES CARGO(ID_CARGO),
CPF VARCHAR(11)  UNIQUE NOT NULL,
NOME VARCHAR(50) NOT NULL,
SALARIO FLOAT NOT NULL,
CONSTRAINT CPF_TAMANHO CHECK (CHAR_LENGTH(CPF) = 11));

CREATE TABLE FABRICANTE_PECA(
ID_FABRICANTE INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL);

CREATE TABLE PECA(
ID_PECA INT NOT NULL PRIMARY KEY,
ID_FABRICANTE INT NOT NULL REFERENCES FABRICANTE_PECA(ID_FABRICANTE),
NOME VARCHAR(50) NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,
ESTOQUE INT NOT NULL);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL PRIMARY KEY,
CPF VARCHAR(11)  UNIQUE NOT NULL,
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(13) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CONSTRAINT CPF_TAMANHO CHECK (CHAR_LENGTH(CPF) = 11),
CONSTRAINT TELEFONE_TAMANHO CHECK (CHAR_LENGTH(TELEFONE) BETWEEN 12 AND 13));

CREATE TABLE POSSE(
ID_POSSE INT NOT NULL PRIMARY KEY,
ID_VEICULO INT NOT NULL REFERENCES VEICULO(ID_VEICULO),
ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID_CLIENTE));

CREATE TABLE SERVICO
(ID_SERVICO INT NOT NULL PRIMARY KEY,
ID_FUNCIONARIO INT REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
DESCRICAO VARCHAR(200),
VALOR FLOAT NOT NULL);

CREATE TABLE OS
(ID_OS INT NOT NULL PRIMARY KEY,
ID_POSSE INT NOT NULL REFERENCES POSSE(ID_POSSE),
ID_SERVICO INT REFERENCES SERVICO(ID_SERVICO),
ID_PECA INT REFERENCES PECA(ID_PECA),
DT_ABRE_OS DATE NOT NULL,
DT_FECHA_OS DATE NOT NULL,
STATUS VARCHAR(1) NOT NULL CHECK (STATUS = 'A' OR STATUS = 'F'),
VALOR_FINAL FLOAT NOT NULL,
DT_HORA_OS TIMESTAMP DEFAULT NOW());

-- INSERTS

-- FABRICANTE_MARCA
INSERT INTO FABRICANTE_MARCA (ID_FABRICANTE, NOME) VALUES
(1, 'Fabrica da Toyota'),
(2, 'Fabrica da Volkswagen'),
(3, 'Fabrica da Chevrolet'),
(4, 'Fabrica da Volvo'),
(5, 'Fabrica da Audi'),
(6, 'Fabrica da BMW'),
(7, 'Fabrica da Porsche'),
(8, 'Fabrica da Ferrari'),
(9, 'Fabrica da Koenigsegg'),
(10, 'Fabrica da BYD');

-- MARCA
INSERT INTO MARCA (ID_MARCA, ID_FABRICANTE, NOME) VALUES
(1, 1, 'Toyota'),
(2, 2, 'Volkswagen'),
(3, 3, 'Chevrolet'),
(4, 4, 'Volvo'),
(5, 5, 'Audi'),
(6, 6, 'BMW'),
(7, 7, 'Porsche'),
(8, 8, 'Ferrari'),
(9, 9, 'Koenigsegg'),
(10, 10, 'BYD');

-- MODELO
INSERT INTO MODELO (ID_MODELO, ID_MARCA, NOME) VALUES
(1, 1, 'Corolla'),
(2, 1, 'Hilux'),
(3, 2, 'Polo'),
(4, 2, 'Nivus'),
(5, 3, 'Opala'),
(6, 3, 'Prisma'),
(7, 4, 'XC60'),
(8, 4, 'XC90'),
(9, 5, 'A3'),
(10, 5, 'Q5'),
(11, 6, '320i'),
(12, 6, 'X1'),
(13, 7, '911'),
(14, 7, 'Macan'),
(15, 8, 'F8 Tributo'),
(16, 8, 'Roma'),
(17, 9, 'Jesko'),
(18, 9, 'Agera RS'),
(19, 10, 'Dolphin'),
(20, 10, 'Seal');

-- CLIENTE
INSERT INTO CLIENTE (ID_CLIENTE, CPF, NOME, TELEFONE, EMAIL) VALUES
(1, '11111111111', 'Thiago Elias', '5586999999999', 'Thiago.Elias@email.com'),
(2, '22222222222', 'João Carlos', '5586888888888', 'joao.carlos@email.com'),
(3, '33333333333', 'Guilherme Alves', '5586777777777', 'Guilherme.alves@email.com'),
(4, '44444444444', 'Matheus Ylan', '5586666666666', 'Matheus.Ylan@email.com'),
(5, '55555555555', 'Max Verstappen', '5586555555555', 'Max.Verstappen@email.com'),
(6, '66666666666', 'Joseph Joestar', '5586444444444', 'Jojo.BattleTendency@email.com'),
(7, '77777777777', 'Cristiano Ronaldo', '5586333333333', 'Cristiano.Ronaldo@email.com'),
(8, '88888888888', 'Steven Stone', '5586222222222', 'Steven.Stone@email.com'),
(9, '99999999999', 'Trevor Belmont', '5586111111111', 'Trevor.Belmont@email.com'),
(10, '00000000000', 'Zagreu', '5586000000000', 'Zagreu.Hades@email.com');

-- FABRICANTE_PECA
INSERT INTO FABRICANTE_PECA (ID_FABRICANTE, NOME) VALUES
(1, 'Bosch'),
(2, 'Nakata'),
(3, 'Denso'),
(4, 'Mahle'),
(5, 'Axios'),
(6, 'Fremax'),
(7, 'Bridgestone');

-- PECA
INSERT INTO PECA (ID_PECA,ID_FABRICANTE, NOME, VALOR_UNITARIO, ESTOQUE) VALUES
(1, 1, 'VELA DE IGNIÇÃO', 350.00, 10),
(2, 1, 'BATERIA AUTOMATIVA', 85.50, 25),
(3, 2, 'AMORTECEDOR', 190.00, 8),
(4, 3, 'BICO INJETOR',540.00, 5),
(5, 4, 'FILTRO DE ÓLEO', 42.00, 50),
(6, 5, 'BUCHA DE SUSPENSÃO', 65.00, 30),
(7, 6, 'DISCO DE FREIO', 220.00, 12),
(8, 7, 'PNEU', 480.00, 16),
(9, 2, 'TERMINAL DE DIREÇÃO', 115.00, 14),
(10, 4, 'PISTÃO DE MOTOR', 95.00, 40);

-- CARGO
INSERT INTO CARGO (ID_CARGO, NOME, COMISSAO) VALUES
(1, 'Mecânico Senior', 0.75),
(2, 'Mecânico Pleno', 0.50),
(3, 'Mecânico Junior', 0.30),
(4, 'Auxiliar de Mecânico', 0.10),
(5, 'Eletricista Automotivo', 0.60),
(6, 'Mecânico Funileiro', 0.40),
(7, 'Alinhador', 0.25),
(8, 'Borracheiro', 0.20);

-- FUNCIONARIO
INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, ID_CARGO, CPF, NOME, SALARIO) VALUES
(1, 1, '11111111111', 'Neymar Junior', 4500.00),
(2, 2, '22222222222', 'Lewis Hamilton', 3800.00),
(3, 3, '33333333333', 'Leon Kennedy', 2800.00),
(4, 4, '44444444444', 'Johnny Joestar', 1800.00),
(5, 5, '55555555555', 'Vaas Montenegro', 4000.00),
(6, 6, '66666666666', 'Carl Johnson', 3200.00),
(7, 7, '77777777777', 'Pierre Stardew Valley', 2500.00),
(8, 8, '88888888888', 'Monkey D. Luffy', 2200.00),
(9, 2, '99999999999', 'Ichigo Kurosaki', 3800.00),
(10, 1, '00000000000', 'Axl Rose', 4600.00);

-- SERVICO
INSERT INTO SERVICO (ID_SERVICO, ID_FUNCIONARIO, DESCRICAO, VALOR) VALUES
(1, 1, 'Troca de pastilhas de freio e alinhamento', 200.00),
(2, 5, 'Instalação de kit multimídia', 350.00),
(3, 6, 'Alinhamento 3D e pintura de para-choque', 400.00),
(4, 8, 'Troca de pneus e balanceamento', 150.00),
(5, 2, 'Revisão completa de 10.000km', 600.00),
(6, 7, 'Alinhamento 3D', 120.00),
(7, 3, 'Troca de óleo e filtro', 80.00),
(8, 1, 'Retífica preventiva de motor', 1500.00),
(9, 9, 'Troca de kit de embreagem', 450.00),
(10, 4, 'Limpeza de bicos injetores', 180.00);

-- VEICULO
INSERT INTO VEICULO (ID_VEICULO, ID_MODELO,PLACA, ANO, COR) VALUES
(1, 1,'NEC5146', 2023, 'Cinza'),
(2, 3,'MDI0839', 2020, 'Branco'),
(3, 5,'IHA2714', 1988, 'Preto'),
(4, 7,'MYO4449', 2022, 'Prata'),
(5, 11,'LKX9822', 2021, 'Azul'),
(6, 13,'HQS1905', 2024, 'Vermelho'),
(7, 19,'NBX9018', 2023, 'Branco'),
(8, 2,'MVL4749', 2018, 'Prata'),
(9, 15,'BTR5075', 2022, 'Amarelo'),
(10, 10,'JYE8823', 2021, 'Preto');

-- INSERT POSSE
INSERT INTO POSSE (ID_POSSE, ID_VEICULO, ID_CLIENTE) VALUES 
(1, 1, 1),
(2, 2, 2),
(3, 3, 3),
(4, 4, 4),
(5, 5, 5),
(6, 6, 6),
(7, 7, 7),
(8, 8, 8),
(9, 9, 9),
(10, 10, 10);

-- OS
INSERT INTO OS (ID_OS, ID_POSSE, ID_SERVICO, ID_PECA, DT_ABRE_OS, DT_FECHA_OS, STATUS, VALOR_FINAL,DT_HORA_OS) VALUES
(1, 1, 1, 1, '2026-05-20', '2026-05-25', 'F', 550.00,DEFAULT),
(2, 2, 7, 5, '2026-05-21', '2026-05-21', 'F', 122.00,DEFAULT),
(3, 3, 3, 9, '2026-05-22', '2026-05-24', 'F', 515.00,DEFAULT),
(4, 4, 6, 6, '2026-05-23', '2026-05-23', 'F', 185.00,DEFAULT),
(5, 5, 5, 1, '2026-05-24', '2026-05-25', 'A', 950.00,DEFAULT),
(6, 6, 9, 3, '2026-05-20', '2026-05-22', 'F', 640.00,DEFAULT),
(7, 7, 2, 10, '2026-05-22', '2026-05-23', 'F', 445.00,DEFAULT),
(8, 8, 4, 8, '2026-05-21', '2026-05-21', 'F', 630.00,DEFAULT),
(9, 9, 8, 4, '2026-05-15', '2026-05-25', 'A', 2040.00,DEFAULT),
(10, 10, 10, 2, '2026-05-25', '2026-05-25', 'F', 265.50,DEFAULT);

-- MOSTRAR TODAS AS TABELAS
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema='public' 
AND table_type='BASE TABLE';   

-- DELETAR TODAS AS TABELAS
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
COMMENT ON SCHEMA public IS 'standard public schema';   

-- SELECTS
SELECT * FROM VEICULO;
SELECT * FROM CARGO;
SELECT * FROM FUNCIONARIO;
SELECT * FROM FABRICANTE_PECA;
SELECT * FROM PECA;
SELECT * FROM FABRICANTE_MARCA;
SELECT * FROM MARCA;
SELECT * FROM MODELO;
SELECT * FROM POSSE;
SELECT * FROM CLIENTE;
SELECT * FROM SERVICO;
SELECT * FROM OS;

-- VIEWS

CREATE OR REPLACE VIEW VISUALIZAR_OS AS
SELECT ID_OS,C.NOME CLIENTE,C.CPF,M.NOME VEICULO,V.PLACA,V.ANO,V.COR,S.DESCRICAO,F.NOME FABRICANTE,
PE.NOME PECA,DT_ABRE_OS,COALESCE(CAST((DT_FECHA_OS) AS VARCHAR),'NÃO FOI FECHADA') DT_FECHA_OS,
STATUS,COALESCE(VALOR_FINAL,0) VALOR_FINAL,DT_HORA_OS
FROM OS O JOIN PECA PE ON PE.ID_PECA = O.ID_PECA JOIN FABRICANTE_PECA F ON F.ID_FABRICANTE = PE.ID_FABRICANTE 
JOIN SERVICO S ON O.ID_SERVICO = S.ID_SERVICO JOIN POSSE PO ON O.ID_POSSE = PO.ID_POSSE 
JOIN CLIENTE C ON PO.ID_CLIENTE = C.ID_CLIENTE JOIN VEICULO V ON PO.ID_VEICULO = V.ID_VEICULO
JOIN MODELO M ON M.ID_MODELO = V.ID_MODELO;

CREATE OR REPLACE VIEW VISUALIZAR_OS_ABERTAS AS
SELECT ID_OS,CLIENTE,CPF,VEICULO,PLACA,ANO,COR,DESCRICAO FROM VISUALIZAR_OS
WHERE STATUS = 'A';

CREATE OR REPLACE VIEW VISUALIZAR_OS_FECHADAS AS
SELECT ID_OS,CLIENTE,CPF,VEICULO,PLACA,ANO,COR,DESCRICAO FROM VISUALIZAR_OS
WHERE STATUS = 'F'; 

-- FUNCTIONS E TRIGGERS DE VALIDAÇÃO
CREATE OR REPLACE FUNCTION VALIDAR_CLIENTE()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_CLIENTE IS NULL) THEN
RAISE EXCEPTION 'O ID DE CLIENTE NÃO PODE SER NULO';
ELSIF (NEW.ID_CLIENTE < 0) THEN
RAISE EXCEPTION 'O ID DE CLIENTE NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_CLIENTE FROM CLIENTE WHERE ID_CLIENTE = NEW.ID_CLIENTE) THEN
RAISE EXCEPTION 'NÃO SÃO PERMITIDOS IDS DUPLICADOS';
ELSIF (NEW.CPF IS NULL) THEN
RAISE EXCEPTION 'O CPF DE CLIENTE NÃO PODE SER NULO';
ELSIF (LENGTH(NEW.CPF) <> 11) THEN
RAISE EXCEPTION 'O CPF INFORMADO DEVE TER 11 DIGITOS';
ELSIF EXISTS(SELECT CPF FROM CLIENTE WHERE CPF = NEW.CPF) THEN
RAISE EXCEPTION 'NÃO SÃO PERMITIDOS CPFS DUPLICADOS';
ELSIF (NEW.NOME IS NULL) THEN
RAISE EXCEPTION 'O NOME INFORMADO NÃO PODE SER NULO';
ELSIF (NEW.TELEFONE IS NULL) THEN
RAISE EXCEPTION 'O TELEFONE INFORMADO NÃO PODE SER NULO';
ELSIF (LENGTH(NEW.TELEFONE) <> 13) THEN
RAISE EXCEPTION 'O TELEFONE DEVE TER 13 DIGITOS';
ELSIF (NEW.EMAIL IS NULL) THEN
RAISE EXCEPTION 'O EMAIL INFORMADO NÃO PODE SER NULO';
ELSIF (NEW.EMAIL NOT ILIKE '%@email.com') THEN
RAISE EXCEPTION 'O EMAIL INFORMADO PRECISA ESTAR NO FORMATO CORRETO';

END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_CLIENTE();
SELECT * FROM CLIENTE;

CREATE FUNCTION CADASTRAR_CLIENTE(ID_CLI INT, CPF VARCHAR, NOME VARCHAR, TELEFONE VARCHAR, EMAIL VARCHAR)
RETURNS VOID AS $$
BEGIN
INSERT INTO CLIENTE VALUES
(ID_CLI,CPF,NOME,TELEFONE,EMAIL);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION VALIDAR_VEICULO()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_VEICULO IS NULL) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER NULO';
ELSIF (NEW.ID_VEICULO < 0) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_VEICULO FROM VEICULO WHERE ID_VEICULO = NEW.ID_VEICULO) THEN
RAISE EXCEPTION 'O ID DE VEICULO NÃO PODE SER DUPLICADO';
ELSIF (NEW.ID_MODELO IS NULL) THEN
RAISE EXCEPTION 'O ID DE MODELO NÃO PODE SER NULO';
ELSIF (NEW.ID_MODELO < 0) THEN
RAISE EXCEPTION 'O ID DE MODELO NÃO PODE SER NEGATIVO';
ELSIF NOT EXISTS (SELECT ID_MODELO FROM MODELO WHERE ID_MODELO = NEW.ID_MODELO) THEN
RAISE EXCEPTION 'O ID DE MODELO PRECISA ESTAR CADASTRADO NO SISTEMA';
ELSIF (NEW.PLACA IS NULL) THEN
RAISE EXCEPTION 'A PLACA INFORMADA NÃO PODE SER NULA';
ELSIF (LENGTH(NEW.PLACA) <> 7) THEN
RAISE EXCEPTION 'A PLACA INFORMADA DEVE TER 7 DIGITOS';
ELSIF (NEW.ANO IS NULL) THEN
RAISE EXCEPTION  'O ANO INFORMADO NÃO PODE SER NULL';
ELSIF (NEW.ANO < 1886 OR NEW.ANO > EXTRACT(YEAR FROM CURRENT_DATE)) THEN
RAISE EXCEPTION 'INSIRA UM ANO DENTRO DE UM LIMITE VALIDO (ENTRE 1886 E O ANO ATUAL)';
ELSIF (NEW.COR IS NULL) THEN
RAISE EXCEPTION 'A COR INFORMADA NÃO PODE SER NULA';
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_VEICULO
BEFORE INSERT ON VEICULO
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_VEICULO();

CREATE OR REPLACE FUNCTION CADASTRAR_VEICULO(ID_CLI INT,ID_VEI INT,ID_MOD INT,PLACA VARCHAR, ANO INT, COR VARCHAR)
RETURNS VOID AS $$
DECLARE
	M_POSSE INT;
BEGIN
SELECT MAX(ID_POSSE) INTO M_POSSE FROM POSSE; 
IF NOT EXISTS(SELECT ID_CLIENTE FROM CLIENTE WHERE ID_CLIENTE = ID_CLI) THEN
RAISE EXCEPTION 'RELACIONE UM CLIENTE EXISTENTE PARA A POSSE DO VEICULO';
ELSIF EXISTS (SELECT ID_VEICULO,ID_CLIENTE FROM POSSE WHERE ID_VEICULO =
ID_VEI AND ID_CLIENTE = ID_CLI) THEN
RAISE EXCEPTION 'ESSE RELAÇÃO DE POSSE JÁ ESTÁ CADASTRADA';
ELSE
INSERT INTO VEICULO VALUES
(ID_VEI,ID_MOD,PLACA,ANO,COR);
INSERT INTO POSSE VALUES
(M_POSSE + 1,ID_VEI,ID_CLI);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO'
END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION VALIDAR_FUNCIONARIO()
RETURNS TRIGGER AS $$
BEGIN
IF (NEW.ID_FUNCIONARIO IS NULL) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NULO';
ELSIF (NEW.ID_FUNCIONARIO < 0) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NEGATIVO';
ELSIF EXISTS (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE ID_FUNCIONARIO = NEW.ID_FUNCIONARIO) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER DUPLICADO';
ELSIF (NEW.ID_CARGO IS NULL) THEN
RAISE EXCEPTION 'ID DO CARGO NÃO PODE SER NULO';
ELSIF (NEW.ID_CARGO < 0) THEN
RAISE EXCEPTION 'ID DO FUNCIONÁRIO NÃO PODE SER NEGATIVO';
ELSIF NOT EXISTS (SELECT ID_CARGO FROM CARGO WHERE ID_CARGO = NEW.ID_CARGO) THEN
RAISE EXCEPTION 'ID DO CARGO PRECISA ESTAR CADASTRADO';
ELSIF (NEW.CPF IS NULL) THEN
RAISE EXCEPTION 'O CPF INFORMADO NÃO DEVE SER NULO';
ELSIF (LENGTH(NEW.CPF) <> 11) THEN 
RAISE EXCEPTION 'O CPF CADASTRADO DEVE TER 11 DIGITOS';
ELSIF EXISTS(SELECT CPF FROM FUNCIONARIO WHERE CPF = NEW.CPF) THEN
RAISE EXCEPTION 'O CPF CADASTRADO NÃO PODE SER DUPLICADO';
ELSIF (NEW.NOME IS NULL) THEN
RAISE EXCEPTION 'O NOME DO FUNCIONARIO NÃO PODE SER NULO';
ELSIF (NEW.SALARIO IS NULL) THEN
RAISE EXCEPTION 'O SALARIO DO FUNCIONÁRIO NÃO PODE SER NULO';
ELSIF (NEW.SALARIO < 1621.00) THEN
RAISE EXCEPTION 'O FUNCIONÁRIO TEM DIREITO A PELO MENOS UM SALÁRIO MINIMO';
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_FUNCIONARIO
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_FUNCIONARIO();

CREATE OR REPLACE FUNCTION CADASTRAR_FUNCIONARIO(ID_FUNC INT,ID_CAR INT,CPF VARCHAR, NOME VARCHAR, SALARIO FLOAT)
RETURNS VOID AS $$
BEGIN
INSERT INTO FUNCIONARIO VALUES
(ID_FUNC,ID_CAR,CPF,NOME,SALARIO);
RAISE NOTICE 'INSERÇÃO FEITA COM SUCESSO';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CALCULAR_COMISSAO(ID_FUNC INT, ANO INT, MES INT)
RETURNS TABLE (
valor_comissao FLOAT
)
AS $$
DECLARE
	O_ANO INT;
	O_MES INT;
BEGIN	
	SELECT EXTRACT (YEAR FROM DT_FECHA_OS) INTO O_ANO
	FROM OS WHERE DT_FECHA_OS IS NOT NULL AND 
	EXTRACT(YEAR FROM DT_FECHA_OS) = ANO;
	
	SELECT EXTRACT (MONTH FROM DT_FECHA_OS) INTO O_MES
	FROM OS WHERE DT_FECHA_OS IS NOT NULL AND 
	EXTRACT(MONTH FROM DT_FECHA_OS) = MES;

	RETURN QUERY
	SELECT (SUM(S.VALOR) * COMISSAO) VALOR_COMISSAO
	FROM OS O JOIN SERVICO S ON O.ID_SERVICO = S.ID_SERVICO
	JOIN FUNCIONARIO F ON S.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN CARGO C ON F.ID_CARGO = C.ID_CARGO
	WHERE DT_FECHA_OS IS NOT NULL AND F.ID_FUNCIONARIO = ID_FUNC AND
	EXTRACT(YEAR FROM DT_FECHA_OS) = O_ANO AND EXTRACT(MONTH FROM DT_FECHA_OS) = O_MES
	GROUP BY F.ID_FUNCIONARIO,F.NOME,COMISSAO
	ORDER BY VALOR_COMISSAO DESC;
END;
$$ LANGUAGE plpgsql;

-- FUNÇÃO DE VALIDAÇÃO
CREATE OR REPLACE FUNCTION VALIDAR_PECA()
RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.VALOR_UNITARIO <= 0) THEN
        RAISE EXCEPTION 'O VALOR UNITÁRIO DA PEÇA DEVE SER MAIOR QUE ZERO.';
    ELSIF (NEW.ESTOQUE <= 0) THEN
        RAISE EXCEPTION 'A QUANTIDADE EM ESTOQUE DEVE SER MAIOR QUE ZERO.';
    ELSIF NOT EXISTS (SELECT 1 FROM FABRICANTE_PECA WHERE ID_FABRICANTE = NEW.ID_FABRICANTE) THEN
        RAISE EXCEPTION 'FABRICANTE INFORMADO NÃO ENCONTRADO NO CADASTRO.';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER DISPARAR_VALIDAR_PECA
BEFORE INSERT OR UPDATE ON PECA 
FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_PECA();

CREATE OR REPLACE FUNCTION CADASTRAR_PECA(
    P_ID_PECA INT, P_ID_FABRICANTE INT, P_NOME VARCHAR, P_VALOR_UNITARIO FLOAT, P_ESTOQUE INT
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO PECA (ID_PECA, ID_FABRICANTE, NOME, VALOR_UNITARIO, ESTOQUE) 
    VALUES (P_ID_PECA, P_ID_FABRICANTE, P_NOME, P_VALOR_UNITARIO, P_ESTOQUE);
    
    RAISE NOTICE 'SUCESSO: PEÇA "%" CADASTRADA COM % UNIDADE(S) A R$ % CADA.', 
                 P_NOME, P_ESTOQUE, P_VALOR_UNITARIO;
END;
$$ LANGUAGE plpgsql;

--REPOR_ESTOQUE
CREATE OR REPLACE FUNCTION REPOR_ESTOQUE(
	P_ID_PECA INT,
 	P_QUANTIDADE INT
)
RETURNS VOID AS $$
DECLARE
	V_NOME_PECA VARCHAR;
	V_ESTOQUE_ANT INT;
	V_ESTOQUE_NOV INT;
BEGIN

	IF (P_QUANTIDADE <= 0) THEN
		RAISE EXCEPTION 'A QUANTIDADE A REPOR DEVE SER MAIOR QUE ZERO.';
	END IF;


	IF NOT EXISTS (SELECT 1 FROM PECA WHERE ID_PECA = P_ID_PECA) THEN
		RAISE EXCEPTION 'PEÇA COM ID % NÃO ENCONTRADA.', P_ID_PECA;
	END IF;
	 
	SELECT NOME, ESTOQUE INTO V_NOME_PECA, V_ESTOQUE_ANT FROM PECA WHERE ID_PECA = P_ID_PECA;

	UPDATE PECA
	SET ESTOQUE = ESTOQUE + P_QUANTIDADE
	WHERE ID_PECA = P_ID_PECA
	RETURNING ESTOQUE INTO V_ESTOQUE_NOV;

	RAISE NOTICE 'SUCESSO: "%" | ESTOQUE ANTERIOR: % -> NOVO ESTOQUE: % (+% UNIDADE(S)).',
		V_NOME_PECA, V_ESTOQUE_ANT, V_ESTOQUE_NOV, P_QUANTIDADE;

END;
$$ LANGUAGE plpgsql;