-- =========================================
-- Projeto final completo do banco de dados
-- =========================================

-- CRIAÇÃO DAS TABELAS
CREATE TABLE FABRICANTE_MARCA(
ID_FABRICANTE INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL);

CREATE TABLE MARCA(
ID_MARCA INT NOT NULL PRIMARY KEY,
ID_FABRICANTE_M INT NOT NULL REFERENCES FABRICANTE_MARCA(ID_FABRICANTE),
NOME VARCHAR(50) NOT NULL);

CREATE TABLE MODELO(
ID_MODELO INT NOT NULL PRIMARY KEY,
ID_MARCA INT NOT NULL REFERENCES MARCA(ID_MARCA),
NOME VARCHAR(50) NOT NULL);

CREATE TABLE VEICULO(
ID_VEICULO INT NOT NULL PRIMARY KEY,
ID_MODELO INT NOT NULL REFERENCES MODELO(ID_MODELO),
ANO INT NOT NULL,
COR VARCHAR(50) NOT NULL);

CREATE TABLE CARGO(
ID_CARGO INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
COMISSAO FLOAT NOT NULL);

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT NOT NULL PRIMARY KEY,
ID_CARGO INT NOT NULL REFERENCES CARGO(ID_CARGO),
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(50) NOT NULL,
SALARIO FLOAT NOT NULL,
CONSTRAINT CPF_TAMANHO CHECK (CHAR_LENGTH(CPF) = 11));

CREATE TABLE FABRICANTE_PECA(
ID_FABRICANTE INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL);

CREATE TABLE PECA(
ID_PECA INT NOT NULL PRIMARY KEY,
ID_FABRICANTE_P INT NOT NULL REFERENCES FABRICANTE_PECA(ID_FABRICANTE),
VALOR_UNITARIO FLOAT NOT NULL,
ESTOQUE INT NOT NULL);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(13) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CONSTRAINT CPF_TAMANHO CHECK (CHAR_LENGTH(CPF) = 11),
CONSTRAINT TELEFONE_TAMANHO CHECK (CHAR_LENGTH(TELEFONE) BETWEEN 12 AND 13));

CREATE TABLE POSSE(
ID_POSSE INT NOT NULL PRIMARY KEY,
ID_VEICULO INT NOT NULL REFERENCES VEICULO(ID_VEICULO),
ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID_CLIENTE));

CREATE TABLE SERVICO
(ID_SERVICO INT NOT NULL PRIMARY KEY,
ID_FUNCIONARIO INT REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
DESCRICAO VARCHAR(200),
VALOR FLOAT NOT NULL);

CREATE TABLE OS
(ID_OS INT NOT NULL PRIMARY KEY,
ID_POSSE INT NOT NULL REFERENCES POSSE(ID_POSSE),
ID_SERVICO INT REFERENCES SERVICO(ID_SERVICO),
ID_PECA INT REFERENCES PECA(ID_PECA),
DT_ABRE_OS DATE NOT NULL,
DT_FECHA_OS DATE,
STATUS VARCHAR(1) CHECK (STATUS = 'A' OR STATUS = 'F')
VALOR_FINAL FLOAT);

-- MOSTRAR TODAS AS TABELAS
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema='public' 
AND table_type='BASE TABLE';   
