-- =========================================
-- Definição das views do banco de dados
-- =========================================

CREATE OR REPLACE VIEW VISUALIZAR_OS AS
SELECT ID_OS,C.NOME CLIENTE,C.CPF,M.NOME VEICULO,V.PLACA,V.ANO,V.COR,S.DESCRICAO,F.NOME FABRICANTE,
PE.NOME PECA,DT_ABRE_OS,COALESCE(CAST((DT_FECHA_OS) AS VARCHAR),'NÃO FOI FECHADA') DT_FECHA_OS,
STATUS,COALESCE(VALOR_FINAL,0) VALOR_FINAL,DT_HORA_OS
FROM OS O JOIN PECA PE ON PE.ID_PECA = O.ID_PECA JOIN FABRICANTE_PECA F ON F.ID_FABRICANTE = PE.ID_FABRICANTE 
JOIN SERVICO S ON O.ID_SERVICO = S.ID_SERVICO JOIN POSSE PO ON O.ID_POSSE = PO.ID_POSSE 
JOIN CLIENTE C ON PO.ID_CLIENTE = C.ID_CLIENTE JOIN VEICULO V ON PO.ID_VEICULO = V.ID_VEICULO
JOIN MODELO M ON M.ID_MODELO = V.ID_MODELO;

CREATE OR REPLACE VIEW VISUALIZAR_OS_ABERTAS AS
SELECT ID_OS,CLIENTE,CPF,VEICULO,PLACA,ANO,COR,DESCRICAO FROM VISUALIZAR_OS
WHERE STATUS = 'A';

CREATE OR REPLACE VIEW VISUALIZAR_OS_FECHADAS AS
SELECT ID_OS,CLIENTE,CPF,VEICULO,PLACA,ANO,COR,DESCRICAO FROM VISUALIZAR_OS
WHERE STATUS = 'F';, 'F', 265.50); 